		<div class="form-field">
			<label for="term_meta[cpt_cols]"><?php _e( 'Number of images in a row', 'sha-sgal' ); ?></label>
			<select name="term_meta[cpt_cols]" id="term_meta[cpt_cols]">
				<?php foreach ( $this->_settings['variants'] as $k => $v ): ?>
					<?php $selected = ( $k == $this->_settings['default'] ) ? ' selected' : ''; ?>
					<?php
            printf(
              '<option value="%s"%s>%s</option>',
              $k,
              $selected,
              __( $v, 'sha-sgal' )
            );
          ?>
				<?php endforeach; ?>
			</select>
			<p class="description"><?php _e( 'Choose a number of images in a row', 'sha-sgal' ); ?></p>
		</div>
		<div class="form-field">
			<label for="term_meta[cpt_thumb_size]"><?php _e( 'Thumbnail size', 'sha-sgal' ); ?></label>
			<select name="term_meta[cpt_thumb_size]" id="term_meta[cpt_thumb_size]">
				<?php foreach (array_keys( $_wp_additional_image_sizes ) as $thumb_size ): ?>
					<?php $selected = ( $k == $this->_settings['default'] ) ? ' selected' : ''; ?>
					<?php
            printf(
              '<option value="%s"%s>%s</option>',
              $thumb_size,
              $selected,
              $_wp_additional_image_sizes[ $thumb_size ]['width'] . 'x' . $_wp_additional_image_sizes[ $thumb_size ]['height']
            );
          ?>
				<?php endforeach; ?>
			</select>
			<p class="description"><?php _e( 'Choose a thumbnail size. Add your own with add_image_size()', 'sha-sgal' ); ?></p>
		</div>
		<div class="form-field">
			<label for="term_meta[cpt_show_gal_name]">
        <input type="hidden" name="term_meta[cpt_show_gal_name]" value="0" />
        <input type="checkbox" name="term_meta[cpt_show_gal_name]" id="term_meta[cpt_show_gal_name]" value="1">
        <?php _e( 'Show Gallery Name', 'sha-sgal' ); ?>
      </label>
			<p class="description"><?php _e( 'Check, if you want to show gallery name', 'sha-sgal' ); ?></p>
		</div>
		<div class="form-field">
			<label for="term_meta[cpt_show_desc]">
        <input type="hidden" name="term_meta[cpt_show_gal_desc]" value="0" />
        <input type="checkbox" name="term_meta[cpt_show_gal_desc]" id="term_meta[cpt_show_gal_desc]" value="1">
        <?php _e( 'Show Gallery Descripion', 'sha-sgal' ); ?>
      </label>
			<p class="description"><?php _e( 'Check, if you want to show gallery description', 'sha-sgal' ); ?></p>
		</div>
