		<tr class="form-field">
			<th scope="row" valign="top">	
				<label for="term_meta[cpt_cols]"><?php _e( 'Number of images in a row', 'sha-sgal' ); ?></label>
			</th>
			<td>
				<select name="term_meta[cpt_cols]" id="term_meta[cpt_cols]">
					<?php foreach ( $this->_settings['variants'] as $k => $v ): ?>
						<?php $selected = ( $k == $term_meta['cpt_cols'] ) ? ' selected' : ''; ?>
						<?php
              printf(
                '<option value="%s"%s>%s</option>',
                $k,
                $selected,
                __( $v, 'sha-sgal' )
              );
            ?>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr class="form-field">
			<th scope="row" valign="top">	
				<label for="term_meta[cpt_thumb_size]"><?php _e( 'Thumbnail size', 'sha-sgal' ); ?></label>
			</th>
			<td>
        <select name="term_meta[cpt_thumb_size]" id="term_meta[cpt_thumb_size]">
          <?php foreach (array_keys( $_wp_additional_image_sizes ) as $thumb_size ): ?>
            <?php $selected = ( $thumb_size == $term_meta['cpt_thumb_size'] ) ? ' selected' : ''; ?>
            <?php
              printf(
                '<option value="%s"%s>%s</option>',
                $thumb_size,
                $selected,
                $_wp_additional_image_sizes[ $thumb_size ]['width'] . 'x' . $_wp_additional_image_sizes[ $thumb_size ]['height']
              );
            ?>
          <?php endforeach; ?>
        </select>
			</td>
		</tr>
		<tr class="form-field">
			<th scope="row" valign="top">	
				<label for="term_meta[cpt_show_gal_name]"><?php _e( 'Show Gallery Name', 'sha-sgal' ); ?></label>
			</th>
			<td>
        <?php $checked = ( $term_meta['cpt_show_gal_name'] == 1 ) ? ' checked' : ''; ?>
        <input type="hidden" name="term_meta[cpt_show_gal_name]" value="0" />
				<input type="checkbox" name="term_meta[cpt_show_gal_name]" id="term_meta[cpt_show_gal_name]" value="1"<?php echo $checked; ?>>
			</td>
		</tr>
		<tr class="form-field">
			<th scope="row" valign="top">	
				<label for="term_meta[cpt_show_gal_desc]"><?php _e( 'Show Gallery Descripion', 'sha-sgal' ); ?></label>
			</th>
			<td>
        <?php $checked = ( $term_meta['cpt_show_gal_desc'] == 1 ) ? ' checked' : ''; ?>
        <input type="hidden" name="term_meta[cpt_show_gal_desc]" value="0" />
				<input type="checkbox" name="term_meta[cpt_show_gal_desc]" id="term_meta[cpt_show_gal_desc]" value="1"<?php echo $checked; ?>>
			</td>
		</tr>
